#!/usr/bin/env python3
"""Generate the app's race sound cues as small, original WAV tones (Phase 5 sound).

The race screen plays five short cues that mirror the existing haptics: a soft
tick on each countdown digit, a brighter "go" when the race arms, a beep as each
lap closes, a rising chirp when a lap is a new personal best, and a little triad
on finish. Rather than ship third-party audio (licensing) these are synthesised
from scratch as plain sine tones with short fade envelopes so they never click.

Usage (from the ``python/`` directory)::

    python tools/gen_sound_cues.py            # (re)write apps/mobile/assets/sounds/*.wav
    python tools/gen_sound_cues.py --check    # fail if any committed WAV is stale

``--check`` runs in CI so the committed assets always match this generator (the
tool is the single source of truth, exactly like the seed pipeline).

Stdlib only; no third-party deps.
"""

from __future__ import annotations

import argparse
import io
import math
import struct
import sys
import wave
from pathlib import Path

SAMPLE_RATE = 44_100
AMPLITUDE = 0.32  # headroom so stacked partials never clip

# Repo-root-relative output directory for the bundled assets.
OUT_DIR = Path("apps/mobile/assets/sounds")


def _tone(freqs: list[float], ms: float) -> list[float]:
    """One segment: the mean of `freqs` sine partials over `ms` milliseconds."""
    n = int(SAMPLE_RATE * ms / 1000.0)
    out: list[float] = []
    for i in range(n):
        t = i / SAMPLE_RATE
        sample = sum(math.sin(2 * math.pi * f * t) for f in freqs) / len(freqs)
        out.append(sample)
    return out


def _envelope(samples: list[float], fade_ms: float = 8.0) -> list[float]:
    """Linear fade in/out to kill the start/stop click of a raw sine."""
    fade = max(1, int(SAMPLE_RATE * fade_ms / 1000.0))
    n = len(samples)
    out = list(samples)
    for i in range(min(fade, n)):
        g = i / fade
        out[i] *= g
        out[n - 1 - i] *= g
    return out


def _cue(segments: list[list[float]]) -> bytes:
    """Concatenate segments and render to 16-bit mono PCM WAV bytes."""
    frames: list[float] = []
    for seg in segments:
        frames.extend(_envelope(seg))
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SAMPLE_RATE)
        pcm = b"".join(
            struct.pack("<h", max(-32768, min(32767, int(s * AMPLITUDE * 32767))))
            for s in frames
        )
        w.writeframes(pcm)
    return buf.getvalue()


def cues() -> dict[str, bytes]:
    """Map each asset filename to its rendered WAV bytes."""
    return {
        # Soft, low blip on each 3·2·1 digit.
        "countdown_tick.wav": _cue([_tone([660.0], 70)]),
        # Brighter, longer tone the instant the race arms.
        "countdown_go.wav": _cue([_tone([990.0], 220)]),
        # Neutral beep as a lap closes.
        "lap.wav": _cue([_tone([880.0], 110)]),
        # Two-note rising chirp when a lap is a new personal best.
        "best_lap.wav": _cue([_tone([880.0], 90), _tone([1320.0], 130)]),
        # Little C-E-G triad on finish.
        "finish.wav": _cue(
            [_tone([523.25], 90), _tone([659.25], 90), _tone([783.99], 200)]
        ),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any committed WAV differs from freshly generated bytes",
    )
    args = parser.parse_args(argv)

    # Resolve OUT_DIR from the repo root (two levels up from this file: python/tools/).
    repo_root = Path(__file__).resolve().parents[2]
    out_dir = repo_root / OUT_DIR

    rendered = cues()

    if args.check:
        stale: list[str] = []
        for name, data in rendered.items():
            path = out_dir / name
            if not path.exists() or path.read_bytes() != data:
                stale.append(name)
        if stale:
            print(
                "sound cues are stale; run `python tools/gen_sound_cues.py`:\n  "
                + "\n  ".join(sorted(stale)),
                file=sys.stderr,
            )
            return 1
        print(f"ok: {len(rendered)} sound cues up to date")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    for name, data in rendered.items():
        (out_dir / name).write_bytes(data)
    print(f"wrote {len(rendered)} cues to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
