/**
 * Bundled catalog artwork — lookup and attribution.
 *
 * Photos ship *with* the app rather than being fetched, so the Identify and
 * Garage screens work offline and Redline ID keeps making no network requests at
 * runtime. `artwork.json` and `artworkAssets.ts` are both generated by
 * `python/tools/fetch_catalog_artwork.py`; edit that tool, not these files.
 *
 * Every image is redistributed under the Hot Wheels Wiki's CC BY-SA terms, and
 * each one records *which* basis applies — an explicit `{{Self}}` declaration on
 * the file page, or Fandom's site-wide licensing of user contributions. The
 * credits screen renders that, and `carArtworkCredit` exists so any surface that
 * shows a photo can also show where it came from.
 */
import type { ImageSourcePropType } from "react-native";

import artworkJson from "./artwork.json";
import { ARTWORK_ASSETS } from "./artworkAssets";

/** Why a given image is redistributable. */
export type LicenseBasis = "uploader-self" | "wiki-default";

export interface ArtworkCredit {
  /** Bundled asset filename, e.g. `70-dodge-charger-r-t.jpg`. */
  readonly file: string;
  readonly bytes: number;
  /** Digest of the bundled bytes, so a re-fetch is verifiable. */
  readonly sha256: string;
  /** Original filename on the wiki. */
  readonly wikiFile: string;
  /** Canonical `File:` page — the attribution link. */
  readonly filePage: string;
  readonly uploader: string | null;
  readonly licenseBasis: LicenseBasis;
  /** Raw licensing template on the file page, when it declares one. */
  readonly licenseTemplate: string | null;
}

export interface ArtworkManifest {
  readonly schemaVersion: number;
  readonly generator: string;
  readonly source: {
    readonly name: string;
    readonly pageId: number;
    readonly revisionId: number;
    readonly revisionUrl: string;
  };
  readonly license: {
    readonly name: string;
    readonly abbreviation: string;
    readonly url: string;
    readonly wikiCopyrightUrl: string;
    /** CC BY-SA obliges us to state what we changed. */
    readonly modifications: string;
    readonly basisCounts: Readonly<Record<string, number>>;
  };
  readonly uploaders: readonly string[];
  readonly imageCount: number;
  readonly images: Readonly<Record<string, ArtworkCredit>>;
}

export const ARTWORK = artworkJson as ArtworkManifest;

/** Uploaders to credit, alphabetical. */
export const ARTWORK_UPLOADERS: readonly string[] = ARTWORK.uploaders;

/** How many catalog cars ship with a photo. */
export const ARTWORK_COUNT: number = Object.keys(ARTWORK.images).length;

/**
 * The bundled image for a car, or `undefined` when it has none — roughly a tenth
 * of the catalog has no usable wiki photo, and those fall back to a placeholder.
 */
export function carArtwork(
  carId: string | null | undefined,
): ImageSourcePropType | undefined {
  if (!carId) return undefined;
  return ARTWORK_ASSETS[carId];
}

/** Attribution for a car's bundled image, or `undefined` when it has none. */
export function carArtworkCredit(
  carId: string | null | undefined,
): ArtworkCredit | undefined {
  if (!carId) return undefined;
  return ARTWORK.images[carId];
}
