/**
 * Static asset map for bundled catalog artwork.
 *
 * @generated by python/tools/fetch_catalog_artwork.py — do not edit by hand.
 *
 * Metro resolves asset paths at build time, so this map has to be literal.
 * Attribution and licensing for every entry live in artwork.json.
 */
import type { ImageSourcePropType } from "react-native";

import img_12_ford_fiesta from "../../assets/catalog/12-ford-fiesta.jpg";
import img_15_dodge_charger_srt from "../../assets/catalog/15-dodge-charger-srt.jpg";
import img_15_dodge_charger_srt_gtd66 from "../../assets/catalog/15-dodge-charger-srt-gtd66.jpg";
import img_15_jaguar_f_type_project_7 from "../../assets/catalog/15-jaguar-f-type-project-7.png";
import img_16_bugatti_chiron from "../../assets/catalog/16-bugatti-chiron.jpg";
import img_16_lamborghini_centenario_roadster from "../../assets/catalog/16-lamborghini-centenario-roadster.jpg";
import img_16_mercedes_amg_gt3 from "../../assets/catalog/16-mercedes-amg-gt3.jpg";
import img_17_nissan_gt_r_r35 from "../../assets/catalog/17-nissan-gt-r-r35.jpg";
import img_17_nissan_gt_r_r35_gmk79 from "../../assets/catalog/17-nissan-gt-r-r35-gmk79.jpg";
import img_18_camaro_ss from "../../assets/catalog/18-camaro-ss.jpg";
import img_19_acura_nsx from "../../assets/catalog/19-acura-nsx.jpg";
import img_19_ford_ranger_raptor from "../../assets/catalog/19-ford-ranger-raptor.jpg";
import img_2014_corvette_c7_r from "../../assets/catalog/2014-corvette-c7-r.jpg";
import img_2016_mercedes_amg_gt from "../../assets/catalog/2016-mercedes-amg-gt.jpg";
import img_2018_honda_civic_type_r from "../../assets/catalog/2018-honda-civic-type-r.jpg";
import img_2020_corvette from "../../assets/catalog/2020-corvette.jpg";
import img_56_chevy_bel_air from "../../assets/catalog/56-chevy-bel-air.jpg";
import img_69_copo_camaro from "../../assets/catalog/69-copo-camaro.jpg";
import img_69_copo_camaro_gtd68 from "../../assets/catalog/69-copo-camaro-gtd68.jpg";
import img_70_dodge_charger_r_t from "../../assets/catalog/70-dodge-charger-r-t.jpg";
import img_70_dodge_charger_r_t_gjp07 from "../../assets/catalog/70-dodge-charger-r-t-gjp07.jpg";
import img_70_ford_escort_rs1600 from "../../assets/catalog/70-ford-escort-rs1600.jpg";
import img_70_ford_escort_rs1600_gjp05 from "../../assets/catalog/70-ford-escort-rs1600-gjp05.jpg";
import img_71_lamborghini_miura_p400_sv from "../../assets/catalog/71-lamborghini-miura-p400-sv.jpg";
import img_71_lamborghini_miura_sv from "../../assets/catalog/71-lamborghini-miura-sv.jpg";
import img_95_mazda_rx_7_drift from "../../assets/catalog/95-mazda-rx-7-drift.jpg";
import img_arachnorod from "../../assets/catalog/arachnorod.jpg";
import img_arachnorod_gtd67 from "../../assets/catalog/arachnorod-gtd67.jpg";
import img_asphalt_assault from "../../assets/catalog/asphalt-assault.jpg";
import img_aston_martin_one_77 from "../../assets/catalog/aston-martin-one-77.jpg";
import img_aston_martin_one_77_gjp01 from "../../assets/catalog/aston-martin-one-77-gjp01.jpg";
import img_aston_martin_vantage_gt3 from "../../assets/catalog/aston-martin-vantage-gt3.jpg";
import img_audi_r8_lms from "../../assets/catalog/audi-r8-lms.jpg";
import img_audi_r8_lms_hbf98 from "../../assets/catalog/audi-r8-lms-hbf98.jpg";
import img_automobili_pininfarina_battista from "../../assets/catalog/automobili-pininfarina-battista.jpg";
import img_back_to_the_future_time_machine from "../../assets/catalog/back-to-the-future-time-machine.jpg";
import img_back_to_the_future_time_machine_hbg26 from "../../assets/catalog/back-to-the-future-time-machine-hbg26.jpg";
import img_batman_arkham_asylum_batmobile from "../../assets/catalog/batman-arkham-asylum-batmobile.jpg";
import img_batman_arkham_knight_batmobile from "../../assets/catalog/batman-arkham-knight-batmobile.jpg";
import img_batman_arkham_knight_batmobile_gtd61 from "../../assets/catalog/batman-arkham-knight-batmobile-gtd61.jpg";
import img_batman_classic_tv_series_batmobile from "../../assets/catalog/batman-classic-tv-series-batmobile.jpg";
import img_batmobile from "../../assets/catalog/batmobile.jpg";
import img_bmw_i8_roadster from "../../assets/catalog/bmw-i8-roadster.jpg";
import img_bone_shaker from "../../assets/catalog/bone-shaker.jpg";
import img_bone_shaker_gjp06 from "../../assets/catalog/bone-shaker-gjp06.jpg";
import img_bone_shaker_gwt05 from "../../assets/catalog/bone-shaker-gwt05.jpg";
import img_bull_whip from "../../assets/catalog/bull-whip.jpg";
import img_buns_of_steel from "../../assets/catalog/buns-of-steel.jpg";
import img_custom_15_ford_mustang from "../../assets/catalog/custom-15-ford-mustang.jpg";
import img_custom_18_ford_mustang_gt from "../../assets/catalog/custom-18-ford-mustang-gt.jpg";
import img_custom_67_pontiac_firebird from "../../assets/catalog/custom-67-pontiac-firebird.jpg";
import img_darth_vader from "../../assets/catalog/darth-vader.jpg";
import img_driftsta from "../../assets/catalog/driftsta.jpg";
import img_dune_daddy from "../../assets/catalog/dune-daddy.jpg";
import img_fiat_500e from "../../assets/catalog/fiat-500e.jpg";
import img_ford_bronco_r from "../../assets/catalog/ford-bronco-r.jpg";
import img_ford_rs200 from "../../assets/catalog/ford-rs200.jpg";
import img_freightliner_race_truck from "../../assets/catalog/freightliner-race-truck.jpg";
import img_gotta_go_2 from "../../assets/catalog/gotta-go-2.jpg";
import img_gt_hunter from "../../assets/catalog/gt-hunter.jpg";
import img_gt_hunter_fxb53 from "../../assets/catalog/gt-hunter-fxb53.jpg";
import img_gt_hunter_gtd62 from "../../assets/catalog/gt-hunter-gtd62.jpg";
import img_hiway_hauler_3_0 from "../../assets/catalog/hiway-hauler-3-0.jpg";
import img_howlin_heat from "../../assets/catalog/howlin-heat.jpg";
import img_huayra_roadster from "../../assets/catalog/huayra-roadster.jpg";
import img_hw50_concept from "../../assets/catalog/hw50-concept.jpg";
import img_jaguar_i_pace_etrophy from "../../assets/catalog/jaguar-i-pace-etrophy.jpg";
import img_jeep_dj_express from "../../assets/catalog/jeep-dj-express.jpg";
import img_jurassic_park_jeep from "../../assets/catalog/jurassic-park-jeep.jpg";
import img_justice_league_batmobile from "../../assets/catalog/justice-league-batmobile.jpg";
import img_justice_league_batmobile_hbf92 from "../../assets/catalog/justice-league-batmobile-hbf92.jpg";
import img_k_i_t_t from "../../assets/catalog/k-i-t-t.jpg";
import img_lamborghini_aventador_lp_700_4 from "../../assets/catalog/lamborghini-aventador-lp-700-4.jpg";
import img_mach_speeder from "../../assets/catalog/mach-speeder.jpg";
import img_mclaren_f1_gtr from "../../assets/catalog/mclaren-f1-gtr.jpg";
import img_mclaren_senna from "../../assets/catalog/mclaren-senna.jpg";
import img_mercedes_benz_unimog_1300l from "../../assets/catalog/mercedes-benz-unimog-1300l.jpg";
import img_motosaurus from "../../assets/catalog/motosaurus.jpg";
import img_motosaurus_gjp00 from "../../assets/catalog/motosaurus-gjp00.jpg";
import img_night_burner from "../../assets/catalog/night-burner.jpg";
import img_night_burner_gml25 from "../../assets/catalog/night-burner-gml25.jpg";
import img_night_shifter from "../../assets/catalog/night-shifter.jpg";
import img_night_shifter_gjp04 from "../../assets/catalog/night-shifter-gjp04.jpg";
import img_nissan_fairlady_z from "../../assets/catalog/nissan-fairlady-z.jpg";
import img_nissan_silvia_s14_drift from "../../assets/catalog/nissan-silvia-s14-drift.jpg";
import img_nissan_skyline_gt_r_bnr34 from "../../assets/catalog/nissan-skyline-gt-r-bnr34.jpg";
import img_nissan_skyline_gt_r_bnr34_hcj08 from "../../assets/catalog/nissan-skyline-gt-r-bnr34-hcj08.jpg";
import img_oval_drive from "../../assets/catalog/oval-drive.jpg";
import img_pagani_huayra from "../../assets/catalog/pagani-huayra.jpg";
import img_pagani_huayra_gtd64 from "../../assets/catalog/pagani-huayra-gtd64.jpg";
import img_porsche_911_gt3_rs from "../../assets/catalog/porsche-911-gt3-rs.jpg";
import img_porsche_918_spyder from "../../assets/catalog/porsche-918-spyder.jpg";
import img_porsche_taycan_turbo_s from "../../assets/catalog/porsche-taycan-turbo-s.jpg";
import img_porsche_taycan_turbo_s_gtd65 from "../../assets/catalog/porsche-taycan-turbo-s-gtd65.jpg";
import img_power_24_gt from "../../assets/catalog/power-24-gt.jpg";
import img_rally_finale from "../../assets/catalog/rally-finale.jpg";
import img_rally_finale_gfp20 from "../../assets/catalog/rally-finale-gfp20.jpg";
import img_rig_heat from "../../assets/catalog/rig-heat.jpg";
import img_rip_rod from "../../assets/catalog/rip-rod.jpg";
import img_rodger_dodger from "../../assets/catalog/rodger-dodger.jpg";
import img_rodger_dodger_gml39 from "../../assets/catalog/rodger-dodger-gml39.jpg";
import img_scorpedo from "../../assets/catalog/scorpedo.jpg";
import img_shark_hammer_2_0 from "../../assets/catalog/shark-hammer-2-0.jpg";
import img_solid_muscle from "../../assets/catalog/solid-muscle.jpg";
import img_speed_dozer from "../../assets/catalog/speed-dozer.jpg";
import img_srt_viper_gts_r from "../../assets/catalog/srt-viper-gts-r.jpg";
import img_sting_rod_ii from "../../assets/catalog/sting-rod-ii.jpg";
import img_subaru_brz from "../../assets/catalog/subaru-brz.jpg";
import img_super_blitzen from "../../assets/catalog/super-blitzen.jpg";
import img_super_blitzen_gfp20 from "../../assets/catalog/super-blitzen-gfp20.jpg";
import img_supercharged from "../../assets/catalog/supercharged.jpg";
import img_tankful from "../../assets/catalog/tankful.jpg";
import img_tesla_cybertruck from "../../assets/catalog/tesla-cybertruck.jpg";
import img_tesla_model_s from "../../assets/catalog/tesla-model-s.jpg";
import img_tesla_roadster from "../../assets/catalog/tesla-roadster.jpg";
import img_the_dark_knight_batmobile from "../../assets/catalog/the-dark-knight-batmobile.jpg";
import img_the_joker_shaker from "../../assets/catalog/the-joker-shaker.jpg";
import img_the_mystery_machine from "../../assets/catalog/the-mystery-machine.jpg";
import img_the_mystery_machine_gvy30 from "../../assets/catalog/the-mystery-machine-gvy30.jpg";
import img_time_attaxi from "../../assets/catalog/time-attaxi.jpg";
import img_time_attaxi_gjp02 from "../../assets/catalog/time-attaxi-gjp02.jpg";
import img_time_shifter from "../../assets/catalog/time-shifter.jpg";
import img_track_manga from "../../assets/catalog/track-manga.jpg";
import img_track_ripper from "../../assets/catalog/track-ripper.jpg";
import img_tv_series_batmobile from "../../assets/catalog/tv-series-batmobile.jpg";
import img_tv_series_batmobile_gjp03 from "../../assets/catalog/tv-series-batmobile-gjp03.jpg";
import img_twin_mill from "../../assets/catalog/twin-mill.jpg";
import img_twin_mill_fxb53 from "../../assets/catalog/twin-mill-fxb53.jpg";
import img_twin_mill_gml08 from "../../assets/catalog/twin-mill-gml08.jpg";
import img_twin_mill_gtd63 from "../../assets/catalog/twin-mill-gtd63.jpg";
import img_volkswagen_beetle from "../../assets/catalog/volkswagen-beetle.jpg";
import img_volkswagen_t1_gtr from "../../assets/catalog/volkswagen-t1-gtr.jpg";
import img_volkswagen_t1_gtr_gml27 from "../../assets/catalog/volkswagen-t1-gtr-gml27.jpg";
import img_west_coast_flyer from "../../assets/catalog/west-coast-flyer.jpg";
import img_x_steam from "../../assets/catalog/x-steam.jpg";

export const ARTWORK_ASSETS: Readonly<Record<string, ImageSourcePropType>> = {
  "12-ford-fiesta": img_12_ford_fiesta,
  "15-dodge-charger-srt": img_15_dodge_charger_srt,
  "15-dodge-charger-srt-gtd66": img_15_dodge_charger_srt_gtd66,
  "15-jaguar-f-type-project-7": img_15_jaguar_f_type_project_7,
  "16-bugatti-chiron": img_16_bugatti_chiron,
  "16-lamborghini-centenario-roadster": img_16_lamborghini_centenario_roadster,
  "16-mercedes-amg-gt3": img_16_mercedes_amg_gt3,
  "17-nissan-gt-r-r35": img_17_nissan_gt_r_r35,
  "17-nissan-gt-r-r35-gmk79": img_17_nissan_gt_r_r35_gmk79,
  "18-camaro-ss": img_18_camaro_ss,
  "19-acura-nsx": img_19_acura_nsx,
  "19-ford-ranger-raptor": img_19_ford_ranger_raptor,
  "2014-corvette-c7-r": img_2014_corvette_c7_r,
  "2016-mercedes-amg-gt": img_2016_mercedes_amg_gt,
  "2018-honda-civic-type-r": img_2018_honda_civic_type_r,
  "2020-corvette": img_2020_corvette,
  "56-chevy-bel-air": img_56_chevy_bel_air,
  "69-copo-camaro": img_69_copo_camaro,
  "69-copo-camaro-gtd68": img_69_copo_camaro_gtd68,
  "70-dodge-charger-r-t": img_70_dodge_charger_r_t,
  "70-dodge-charger-r-t-gjp07": img_70_dodge_charger_r_t_gjp07,
  "70-ford-escort-rs1600": img_70_ford_escort_rs1600,
  "70-ford-escort-rs1600-gjp05": img_70_ford_escort_rs1600_gjp05,
  "71-lamborghini-miura-p400-sv": img_71_lamborghini_miura_p400_sv,
  "71-lamborghini-miura-sv": img_71_lamborghini_miura_sv,
  "95-mazda-rx-7-drift": img_95_mazda_rx_7_drift,
  "arachnorod": img_arachnorod,
  "arachnorod-gtd67": img_arachnorod_gtd67,
  "asphalt-assault": img_asphalt_assault,
  "aston-martin-one-77": img_aston_martin_one_77,
  "aston-martin-one-77-gjp01": img_aston_martin_one_77_gjp01,
  "aston-martin-vantage-gt3": img_aston_martin_vantage_gt3,
  "audi-r8-lms": img_audi_r8_lms,
  "audi-r8-lms-hbf98": img_audi_r8_lms_hbf98,
  "automobili-pininfarina-battista": img_automobili_pininfarina_battista,
  "back-to-the-future-time-machine": img_back_to_the_future_time_machine,
  "back-to-the-future-time-machine-hbg26": img_back_to_the_future_time_machine_hbg26,
  "batman-arkham-asylum-batmobile": img_batman_arkham_asylum_batmobile,
  "batman-arkham-knight-batmobile": img_batman_arkham_knight_batmobile,
  "batman-arkham-knight-batmobile-gtd61": img_batman_arkham_knight_batmobile_gtd61,
  "batman-classic-tv-series-batmobile": img_batman_classic_tv_series_batmobile,
  "batmobile": img_batmobile,
  "bmw-i8-roadster": img_bmw_i8_roadster,
  "bone-shaker": img_bone_shaker,
  "bone-shaker-gjp06": img_bone_shaker_gjp06,
  "bone-shaker-gwt05": img_bone_shaker_gwt05,
  "bull-whip": img_bull_whip,
  "buns-of-steel": img_buns_of_steel,
  "custom-15-ford-mustang": img_custom_15_ford_mustang,
  "custom-18-ford-mustang-gt": img_custom_18_ford_mustang_gt,
  "custom-67-pontiac-firebird": img_custom_67_pontiac_firebird,
  "darth-vader": img_darth_vader,
  "driftsta": img_driftsta,
  "dune-daddy": img_dune_daddy,
  "fiat-500e": img_fiat_500e,
  "ford-bronco-r": img_ford_bronco_r,
  "ford-rs200": img_ford_rs200,
  "freightliner-race-truck": img_freightliner_race_truck,
  "gotta-go-2": img_gotta_go_2,
  "gt-hunter": img_gt_hunter,
  "gt-hunter-fxb53": img_gt_hunter_fxb53,
  "gt-hunter-gtd62": img_gt_hunter_gtd62,
  "hiway-hauler-3-0": img_hiway_hauler_3_0,
  "howlin-heat": img_howlin_heat,
  "huayra-roadster": img_huayra_roadster,
  "hw50-concept": img_hw50_concept,
  "jaguar-i-pace-etrophy": img_jaguar_i_pace_etrophy,
  "jeep-dj-express": img_jeep_dj_express,
  "jurassic-park-jeep": img_jurassic_park_jeep,
  "justice-league-batmobile": img_justice_league_batmobile,
  "justice-league-batmobile-hbf92": img_justice_league_batmobile_hbf92,
  "k-i-t-t": img_k_i_t_t,
  "lamborghini-aventador-lp-700-4": img_lamborghini_aventador_lp_700_4,
  "mach-speeder": img_mach_speeder,
  "mclaren-f1-gtr": img_mclaren_f1_gtr,
  "mclaren-senna": img_mclaren_senna,
  "mercedes-benz-unimog-1300l": img_mercedes_benz_unimog_1300l,
  "motosaurus": img_motosaurus,
  "motosaurus-gjp00": img_motosaurus_gjp00,
  "night-burner": img_night_burner,
  "night-burner-gml25": img_night_burner_gml25,
  "night-shifter": img_night_shifter,
  "night-shifter-gjp04": img_night_shifter_gjp04,
  "nissan-fairlady-z": img_nissan_fairlady_z,
  "nissan-silvia-s14-drift": img_nissan_silvia_s14_drift,
  "nissan-skyline-gt-r-bnr34": img_nissan_skyline_gt_r_bnr34,
  "nissan-skyline-gt-r-bnr34-hcj08": img_nissan_skyline_gt_r_bnr34_hcj08,
  "oval-drive": img_oval_drive,
  "pagani-huayra": img_pagani_huayra,
  "pagani-huayra-gtd64": img_pagani_huayra_gtd64,
  "porsche-911-gt3-rs": img_porsche_911_gt3_rs,
  "porsche-918-spyder": img_porsche_918_spyder,
  "porsche-taycan-turbo-s": img_porsche_taycan_turbo_s,
  "porsche-taycan-turbo-s-gtd65": img_porsche_taycan_turbo_s_gtd65,
  "power-24-gt": img_power_24_gt,
  "rally-finale": img_rally_finale,
  "rally-finale-gfp20": img_rally_finale_gfp20,
  "rig-heat": img_rig_heat,
  "rip-rod": img_rip_rod,
  "rodger-dodger": img_rodger_dodger,
  "rodger-dodger-gml39": img_rodger_dodger_gml39,
  "scorpedo": img_scorpedo,
  "shark-hammer-2-0": img_shark_hammer_2_0,
  "solid-muscle": img_solid_muscle,
  "speed-dozer": img_speed_dozer,
  "srt-viper-gts-r": img_srt_viper_gts_r,
  "sting-rod-ii": img_sting_rod_ii,
  "subaru-brz": img_subaru_brz,
  "super-blitzen": img_super_blitzen,
  "super-blitzen-gfp20": img_super_blitzen_gfp20,
  "supercharged": img_supercharged,
  "tankful": img_tankful,
  "tesla-cybertruck": img_tesla_cybertruck,
  "tesla-model-s": img_tesla_model_s,
  "tesla-roadster": img_tesla_roadster,
  "the-dark-knight-batmobile": img_the_dark_knight_batmobile,
  "the-joker-shaker": img_the_joker_shaker,
  "the-mystery-machine": img_the_mystery_machine,
  "the-mystery-machine-gvy30": img_the_mystery_machine_gvy30,
  "time-attaxi": img_time_attaxi,
  "time-attaxi-gjp02": img_time_attaxi_gjp02,
  "time-shifter": img_time_shifter,
  "track-manga": img_track_manga,
  "track-ripper": img_track_ripper,
  "tv-series-batmobile": img_tv_series_batmobile,
  "tv-series-batmobile-gjp03": img_tv_series_batmobile_gjp03,
  "twin-mill": img_twin_mill,
  "twin-mill-fxb53": img_twin_mill_fxb53,
  "twin-mill-gml08": img_twin_mill_gml08,
  "twin-mill-gtd63": img_twin_mill_gtd63,
  "volkswagen-beetle": img_volkswagen_beetle,
  "volkswagen-t1-gtr": img_volkswagen_t1_gtr,
  "volkswagen-t1-gtr-gml27": img_volkswagen_t1_gtr_gml27,
  "west-coast-flyer": img_west_coast_flyer,
  "x-steam": img_x_steam,
};
