/**
 * The Hot Wheels id **car catalog** — real casting names and metadata.
 *
 * `catalog.json` is generated by `python/tools/scrape_id_catalog.py` from a
 * pinned Hot Wheels Wiki revision (the only public record of the 2019–2021 id
 * line, now that Mattel's backend is gone). It is a flat, static list bundled
 * with the app. Third-party artwork is neither bundled nor fetched; provenance
 * and source-license references live in `catalog-provenance.json` (ADR-0013).
 *
 * Identity is manual — a decoded car carries a `castingKey` (model id), and the
 * user picks which catalog entry it is; there is no binary-id → name map to
 * automate. So this module is just the lookup/search surface for that picker
 * and the garage's "what car is this" rendering.
 */
import catalogJson from "./catalog.json";
import provenanceJson from "./catalog-provenance.json";

export interface CatalogCar {
  /** Stable slug (kebab name, `-toy#` suffixed on collisions). Persisted in identifications. */
  readonly id: string;
  /** Casting name as shown on the wiki, e.g. `'70 Dodge Charger R/T`. */
  readonly name: string;
  /** Mattel toy number (e.g. `FXB03`), when known. */
  readonly toyNumber: string | null;
  /** Series / sub-line, e.g. `Speed Demons`. */
  readonly series: string | null;
  /** Release year (2019–2021). */
  readonly year: number | null;
  /** Wave label, e.g. `2019 Series 1`. */
  readonly wave: string | null;
  /** Body colour, when the wiki listed one. */
  readonly bodyColor: string | null;
  /** Always null in release builds; third-party wiki artwork is not redistributed. */
  readonly image: null;
  /** Canonical wiki page for attribution and an explicit user-initiated lookup. */
  readonly wikiPage: string | null;
}

export const CATALOG: readonly CatalogCar[] = catalogJson as CatalogCar[];

export interface CatalogProvenance {
  readonly schemaVersion: number;
  readonly catalog: {
    readonly recordCount: number;
    readonly sha256: string;
  };
  readonly source: {
    readonly name: string;
    readonly pageId: number;
    readonly revisionId: number;
    readonly revisionTimestamp: string;
    readonly revisionUrl: string;
    readonly contributorsUrl: string;
  };
  readonly licensing: readonly {
    readonly name: string;
    readonly url: string;
  }[];
  readonly generator: string;
  readonly artwork: {
    readonly included: false;
    readonly policy: string;
  };
}

export const CATALOG_PROVENANCE = provenanceJson as CatalogProvenance;

/** Index by id for O(1) lookup. */
const BY_ID: ReadonlyMap<string, CatalogCar> = new Map(CATALOG.map((c) => [c.id, c]));

/** Resolve a catalog entry by its stable id, or `undefined` if unknown. */
export function findCatalogCar(id: string | undefined | null): CatalogCar | undefined {
  if (!id) return undefined;
  return BY_ID.get(id);
}

function norm(s: string): string {
  return s.toLowerCase().trim();
}

function includesNormalized(value: string | null, query: string): boolean {
  return value != null && norm(value).includes(query);
}

/**
 * Human-facing catalog metadata in priority order, with empty values removed.
 * Keeps the UI consistent between the identify picker and car detail screen.
 */
export function catalogMeta(car: CatalogCar): string[] {
  return [
    car.series,
    car.wave,
    car.bodyColor ? `${car.bodyColor} body` : null,
    car.year ? String(car.year) : null,
    car.toyNumber,
  ].filter((value): value is string => Boolean(value));
}

/**
 * Rank a car against a normalised query. Higher is better; `null` excludes it.
 * Name matches outrank series/toy-number matches, and a prefix beats a midword
 * hit, so typing "char" surfaces the Chargers first.
 */
function score(car: CatalogCar, q: string): number | null {
  const name = norm(car.name);
  if (name === q) return 100;
  if (name.startsWith(q)) return 80;
  if (name.includes(q)) return 60;
  if (includesNormalized(car.toyNumber, q)) return 40;
  if (includesNormalized(car.series, q)) return 30;
  if (includesNormalized(car.wave, q)) return 25;
  if (includesNormalized(car.bodyColor, q)) return 22;
  if (car.year && String(car.year) === q) return 20;
  return null;
}

/**
 * Search the catalog by name / toy number / series / year. An empty query
 * returns the whole catalog (name-sorted) so the picker can show everything.
 * Results are ranked by {@link score}, then alphabetically by name.
 */
export function searchCatalog(query: string): CatalogCar[] {
  const q = norm(query);
  if (q.length === 0) {
    return [...CATALOG].sort((a, b) => a.name.localeCompare(b.name));
  }
  const scored: { car: CatalogCar; rank: number }[] = [];
  for (const car of CATALOG) {
    const rank = score(car, q);
    if (rank !== null) scored.push({ car, rank });
  }
  scored.sort((a, b) => b.rank - a.rank || a.car.name.localeCompare(b.car.name));
  return scored.map((s) => s.car);
}
