/**
 * The Hot Wheels id **car catalog** — real casting names + photos.
 *
 * `catalog.json` is generated by `python/tools/scrape_id_catalog.py` from the
 * Hot Wheels Fandom wiki (the only public record of the 2019–2021 id line, now
 * that Mattel's backend is gone). It is a flat, static list: the app never
 * fetches it at runtime, it ships in the bundle. Photo URLs hot-link the wiki
 * CDN (content is CC-BY-SA; see ADR-0013).
 *
 * Identity is manual — a decoded car carries a `castingKey` (model id), and the
 * user picks which catalog entry it is; there is no binary-id → name map to
 * automate. So this module is just the lookup/search surface for that picker
 * and the garage's "what car is this" rendering.
 */
import catalogJson from "./catalog.json";

export interface CatalogCar {
  /** Stable slug (kebab name, `-toy#` suffixed on collisions). Persisted in identifications. */
  readonly id: string;
  /** Casting name as shown on the wiki, e.g. `'70 Dodge Charger R/T`. */
  readonly name: string;
  /** Mattel toy number (e.g. `FXB03`), when known. */
  readonly toyNumber: string | null;
  /** Series / sub-line, e.g. `Speed Demons`. */
  readonly series: string | null;
  /** Release year (2019–2021). */
  readonly year: number | null;
  /** Wave label, e.g. `2019 Series 1`. */
  readonly wave: string | null;
  /** Body colour, when the wiki listed one. */
  readonly bodyColor: string | null;
  /** Thumbnail photo URL (wiki CDN), or null when the wiki had no usable image. */
  readonly image: string | null;
  /** Canonical wiki page for attribution / "view more". */
  readonly wikiPage: string | null;
}

export const CATALOG: readonly CatalogCar[] = catalogJson as CatalogCar[];

/** Index by id for O(1) lookup. */
const BY_ID: ReadonlyMap<string, CatalogCar> = new Map(CATALOG.map((c) => [c.id, c]));

export const CATALOG_YEARS: readonly number[] = [
  ...new Set(CATALOG.map((car) => car.year).filter((year): year is number => year !== null)),
].sort((a, b) => a - b);

export const CATALOG_WAVES: readonly string[] = [
  ...new Set(CATALOG.map((car) => car.wave).filter((wave): wave is string => wave !== null)),
].sort((a, b) => a.localeCompare(b));

export interface CatalogFilters {
  readonly year?: number | null;
  readonly wave?: string | null;
  /** Dedicated package lookup; normalized to letters/digits before matching. */
  readonly toyNumber?: string;
}

/** Resolve a catalog entry by its stable id, or `undefined` if unknown. */
export function findCatalogCar(id: string | undefined | null): CatalogCar | undefined {
  if (!id) return undefined;
  return BY_ID.get(id);
}

function norm(s: string): string {
  return s.toLowerCase().trim();
}

export function normalizeToyNumber(value: string): string {
  return value.replace(/[^a-z0-9]/gi, "").toUpperCase();
}

function includesNormalized(value: string | null, query: string): boolean {
  return value != null && norm(value).includes(query);
}

/**
 * Human-facing catalog metadata in priority order, with empty values removed.
 * Keeps the UI consistent between the identify picker and car detail screen.
 */
export function catalogMeta(car: CatalogCar): string[] {
  return [
    car.series,
    car.wave,
    car.bodyColor ? `${car.bodyColor} body` : null,
    car.year ? String(car.year) : null,
    car.toyNumber,
  ].filter((value): value is string => Boolean(value));
}

/**
 * Rank a car against a normalised query. Higher is better; `null` excludes it.
 * Name matches outrank series/toy-number matches, and a prefix beats a midword
 * hit, so typing "char" surfaces the Chargers first.
 */
function score(car: CatalogCar, q: string): number | null {
  const name = norm(car.name);
  if (name === q) return 100;
  if (name.startsWith(q)) return 80;
  if (name.includes(q)) return 60;
  if (includesNormalized(car.toyNumber, q)) return 40;
  if (includesNormalized(car.series, q)) return 30;
  if (includesNormalized(car.wave, q)) return 25;
  if (includesNormalized(car.bodyColor, q)) return 22;
  if (car.year && String(car.year) === q) return 20;
  return null;
}

function toyNumberScore(car: CatalogCar, query: string): number | null {
  const candidate = normalizeToyNumber(car.toyNumber ?? "");
  const wanted = normalizeToyNumber(query);
  if (!wanted || !candidate) return null;
  if (candidate === wanted) return 200;
  if (candidate.startsWith(wanted)) return 120;
  if (candidate.includes(wanted)) return 90;
  return null;
}

/**
 * Search the catalog by name / toy number / series / year. An empty query
 * returns the whole catalog (name-sorted) so the picker can show everything.
 * Results are ranked by {@link score}, then alphabetically by name.
 */
export function searchCatalog(query: string, filters: CatalogFilters = {}): CatalogCar[] {
  const q = norm(query);
  const scored: { car: CatalogCar; rank: number }[] = [];
  for (const car of CATALOG) {
    if (filters.year != null && car.year !== filters.year) continue;
    if (filters.wave && car.wave !== filters.wave) continue;
    const rank = filters.toyNumber
      ? toyNumberScore(car, filters.toyNumber)
      : q.length > 0
        ? score(car, q)
        : 0;
    if (rank !== null) scored.push({ car, rank });
  }
  scored.sort((a, b) => b.rank - a.rank || a.car.name.localeCompare(b.car.name));
  return scored.map((s) => s.car);
}
