import { StyleSheet } from "react-native";

import { colors, fontFamily, fontSize, fontSizeT, fontWeight, radiusT, spacing } from "../../theme/tokens";

/** Shared max column width; the split layout widens only the header past it. */
const COLUMN_MAX_WIDTH = 620;

/**
 * Race cockpit shared styles, on the Trackside Telemetry ramp (proposal B).
 * Geometry (padding, gaps, column widths, hit targets, phase boundaries) is
 * unchanged from the previous shell — only the color/material/typography ramp
 * migrated: void background, panel surfaces with hairlines, flame for the
 * decisive event (primary action, best, active), electric for links/next, and
 * tabular/mono numerals for every timing value. The race engine, haptics, and
 * sound gating are untouched.
 */
export const raceStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.void },
  screenReaderOnly: {
    position: "absolute",
    left: -10000,
    width: 1,
    height: 1,
    overflow: "hidden",
  },
  content: { alignItems: "center", paddingHorizontal: spacing(5), gap: spacing(5) },
  header: {
    width: "100%",
    maxWidth: COLUMN_MAX_WIDTH,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing(3),
  },
  title: { color: colors.ink, fontSize: fontSize.lg, fontWeight: fontWeight.heavy },
  headerWide: { maxWidth: 9999, paddingBottom: spacing(3) },
  headerRight: { flexDirection: "row", alignItems: "center", gap: spacing(3) },

  // Two-pane landscape layout.
  splitRoot: { paddingHorizontal: spacing(5) },
  splitBody: { flex: 1, flexDirection: "row", gap: spacing(6) },
  splitLeft: { flex: 5 },
  splitRight: { flex: 4 },
  splitPane: {
    gap: spacing(5),
    paddingBottom: spacing(8),
    // Centre the pane's content when it is shorter than the window; once it
    // overflows this is a no-op and the pane scrolls from the top as usual.
    flexGrow: 1,
    justifyContent: "center",
  },
  section: { width: "100%", maxWidth: COLUMN_MAX_WIDTH, gap: spacing(3) },
  sectionLabel: {
    color: colors.inkMuted,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  modeToggle: {
    flexDirection: "row",
    gap: spacing(2),
  },
  modeOption: {
    flex: 1,
    minHeight: 76,
    backgroundColor: colors.panelSolid,
    borderColor: colors.hairline,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: radiusT.card,
    padding: spacing(3),
    gap: spacing(1),
  },
  modeOptionActive: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.flame,
  },
  modeTitle: { color: colors.ink, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  modeTitleActive: { color: colors.flame },
  modeDescription: { color: colors.inkMuted, fontSize: fontSize.xs, lineHeight: 16 },
  chips: { flexDirection: "row", gap: spacing(2) },
  chip: {
    flex: 1,
    backgroundColor: colors.panelInset,
    borderColor: colors.hairline,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: radiusT.field,
    paddingVertical: spacing(3),
    alignItems: "center",
    gap: 1,
  },
  chipActive: { backgroundColor: colors.flame, borderColor: colors.flame },
  chipText: {
    color: colors.ink,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.heavy,
    fontVariant: ["tabular-nums"],
  },
  chipUnit: { color: colors.inkMuted, fontSize: fontSize.xs },
  chipTextActive: { color: colors.void },
  input: {
    backgroundColor: colors.panelInset,
    borderColor: colors.hairline,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: radiusT.field,
    paddingHorizontal: spacing(3.5),
    paddingVertical: spacing(3),
    color: colors.ink,
    fontSize: fontSize.md,
  },
  card: {
    width: "100%",
    maxWidth: COLUMN_MAX_WIDTH,
    backgroundColor: colors.panelSolid,
    borderColor: colors.hairline,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: radiusT.card,
    padding: spacing(4),
    gap: spacing(2),
  },
  cardRaised: {
    backgroundColor: colors.panelRaised,
    borderColor: colors.flame,
  },
  cardNext: {
    backgroundColor: colors.accentBlueSoft,
    borderColor: colors.electric,
  },
  cardHeadRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing(2),
  },
  cardHeading: {
    color: colors.inkMuted,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  empty: { color: colors.inkMuted, fontSize: fontSize.sm, lineHeight: 19 },
  carSummary: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing(3),
    flex: 1,
  },
  carText: { flex: 1, gap: spacing(0.5) },
  carName: { color: colors.ink, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  carMeta: { color: colors.inkMuted, fontSize: fontSize.xs },
  readinessPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing(2),
    backgroundColor: colors.panelSolid,
    borderColor: colors.hairline,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: radiusT.pill,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(3),
  },
  readinessDot: { width: 9, height: 9, borderRadius: radiusT.pill },
  readinessLabel: { color: colors.ink, fontSize: fontSize.sm, fontWeight: fontWeight.medium },
  readinessCard: {
    width: "100%",
    maxWidth: COLUMN_MAX_WIDTH,
    backgroundColor: colors.panelSolid,
    borderColor: colors.caution,
    borderWidth: 1,
    borderRadius: radiusT.card,
    padding: spacing(3),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing(3),
  },
  readinessText: { flex: 1, gap: spacing(1) },
  readinessTitle: { color: colors.ink, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  readinessDetail: { color: colors.inkSecondary, fontSize: fontSize.xs, lineHeight: 16 },
  recoveryLink: { color: colors.electric, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  actionRow: { flexDirection: "row", gap: spacing(2) },
  flex1: { flex: 1 },
  primaryBtn: {
    backgroundColor: colors.flame,
    borderRadius: radiusT.field,
    paddingVertical: spacing(3.5),
    paddingHorizontal: spacing(3),
    alignItems: "center",
    justifyContent: "center",
  },
  primaryBtnText: { color: colors.void, fontSize: fontSize.md, fontWeight: fontWeight.heavy },
  ghostBtn: {
    backgroundColor: colors.panelInset,
    borderColor: colors.hairline,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: radiusT.field,
    paddingVertical: spacing(3),
    paddingHorizontal: spacing(3),
    alignItems: "center",
    justifyContent: "center",
  },
  ghostBtnText: { color: colors.ink, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  smallBtn: {
    backgroundColor: colors.panelInset,
    borderColor: colors.hairline,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: radiusT.field,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(2.5),
  },
  smallBtnText: { color: colors.electric, fontSize: fontSize.xs, fontWeight: fontWeight.bold },
  removeBtnText: { color: colors.fault, fontSize: fontSize.xs, fontWeight: fontWeight.bold },
  dangerBtn: {
    backgroundColor: colors.panelSolid,
    borderColor: colors.fault,
    borderWidth: 1,
    borderRadius: radiusT.field,
    paddingVertical: spacing(3.5),
    paddingHorizontal: spacing(3),
    alignItems: "center",
  },
  dangerBtnText: { color: colors.fault, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  btnDisabled: { opacity: 0.45 },
  btnDisabledText: { color: colors.inkMuted },
  pressed: { opacity: 0.7 },
  lineupLabel: {
    color: colors.inkMuted,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  lineupName: { color: colors.ink, fontSize: fontSize.xl, fontWeight: fontWeight.heavy },
  lineupNameNext: { color: colors.ink, fontSize: fontSize.lg, fontWeight: fontWeight.bold },
  lineupActions: { flexDirection: "row", flexWrap: "wrap", gap: spacing(2) },
  queueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing(3),
    paddingVertical: spacing(2.5),
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.hairline,
  },
  queueBody: { flex: 1, gap: spacing(0.5) },
  queueName: { color: colors.ink, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  queueMeta: { color: colors.inkMuted, fontSize: fontSize.xs },
  queueActions: { flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-end", gap: spacing(1.5) },
  countdown: {
    width: "100%",
    maxWidth: COLUMN_MAX_WIDTH,
    alignItems: "center",
    gap: spacing(4),
    paddingVertical: spacing(6),
  },
  countNum: {
    color: colors.flame,
    fontFamily: fontFamily.telemetry,
    fontSize: fontSizeT.raceDisplay,
    fontWeight: fontWeight.heavy,
    fontVariant: ["tabular-nums"],
  },
  countLabel: { color: colors.inkSecondary, fontSize: fontSize.md },
  countNumLarge: { fontSize: 200 },
  racerEyebrow: {
    color: colors.flame,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  racerHeading: { color: colors.ink, fontSize: fontSize.xl, fontWeight: fontWeight.heavy },
  lapHero: { alignItems: "center", paddingVertical: spacing(2), gap: spacing(1) },
  lapHeroNum: {
    color: colors.ink,
    fontFamily: fontFamily.telemetry,
    fontSize: 72,
    fontWeight: fontWeight.heavy,
    fontVariant: ["tabular-nums"],
  },
  lapHeroOf: { color: colors.inkMuted, fontSize: fontSize.xl, fontWeight: fontWeight.bold },
  lapHeroNumLarge: { fontSize: 148 },
  lapHeroLabel: {
    color: colors.inkMuted,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  liveRow: { flexDirection: "row", gap: spacing(2) },
  liveStat: {
    flex: 1,
    backgroundColor: colors.panelSolid,
    borderColor: colors.hairline,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: radiusT.card,
    paddingVertical: spacing(3),
    paddingHorizontal: spacing(2),
    alignItems: "center",
    gap: 2,
  },
  liveStatLabel: {
    color: colors.inkMuted,
    fontSize: fontSize.xs,
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  liveStatValue: {
    color: colors.ink,
    fontFamily: fontFamily.telemetry,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    fontVariant: ["tabular-nums"],
  },
  liveStatValueHot: { color: colors.flame },
  lapRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: spacing(2),
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.hairline,
  },
  lapNum: { color: colors.inkSecondary, fontSize: fontSize.sm, fontVariant: ["tabular-nums"] },
  lapRight: { flexDirection: "row", alignItems: "center", gap: spacing(2) },
  lapTime: {
    color: colors.ink,
    fontFamily: fontFamily.telemetry,
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    fontVariant: ["tabular-nums"],
  },
  lapTimeBest: { color: colors.flame },
  bestTag: { color: colors.flame, fontSize: fontSize.xs, fontWeight: fontWeight.bold, letterSpacing: 1 },
  resultHero: { alignItems: "center", gap: spacing(1), paddingVertical: spacing(2) },
  resultHeroLabel: {
    color: colors.flame,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.heavy,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  resultHeroTime: {
    color: colors.ink,
    fontFamily: fontFamily.telemetry,
    fontSize: 56,
    fontWeight: fontWeight.heavy,
    fontVariant: ["tabular-nums"],
  },
  resultHeroSub: { color: colors.inkSecondary, fontSize: fontSize.sm },
  nextUpText: { color: colors.electric, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  shareBtn: {
    backgroundColor: colors.panelInset,
    borderColor: colors.hairline,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: radiusT.field,
    paddingVertical: spacing(3),
    alignItems: "center",
  },
  shareBtnText: { color: colors.flame, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  clearText: { color: colors.inkMuted, fontSize: fontSize.xs, fontWeight: fontWeight.bold },
  leaderboardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing(3),
    paddingVertical: spacing(2),
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.hairline,
  },
  leaderboardRank: {
    color: colors.inkMuted,
    fontFamily: fontFamily.telemetry,
    fontSize: fontSize.md,
    fontWeight: fontWeight.heavy,
    width: 22,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  leaderboardRankTop: { color: colors.flame },
  leaderboardMid: { flex: 1 },
  leaderboardPlayer: { color: colors.ink, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  leaderboardMeta: { color: colors.inkMuted, fontSize: fontSize.xs },
  leaderboardTime: {
    color: colors.ink,
    fontFamily: fontFamily.telemetry,
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    fontVariant: ["tabular-nums"],
  },
  leaderboardTimeTop: { color: colors.flame },

  // Tournament mode
  tourPill: {
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1),
    borderRadius: radiusT.pill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.hairline,
    backgroundColor: colors.panelInset,
  },
  tourPillOn: { backgroundColor: colors.flame, borderColor: colors.flame },
  tourPillText: { color: colors.inkSecondary, fontSize: fontSize.sm, fontWeight: fontWeight.heavy },
  tourPillTextOn: { color: colors.void },
  champCard: { borderColor: colors.flame, alignItems: "center", gap: spacing(2) },
  champLabel: {
    color: colors.inkMuted,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  champName: { color: colors.ink, fontSize: fontSize.xl, fontWeight: fontWeight.heavy },
  bracketRound: { marginTop: spacing(2), gap: spacing(1) },
  bracketRoundLabel: {
    color: colors.inkMuted,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  bracketMatch: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing(2),
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(2),
    borderRadius: radiusT.field,
    backgroundColor: colors.panelInset,
  },
  bracketMatchActive: { borderWidth: 1, borderColor: colors.electric },
  bracketName: { flex: 1, color: colors.inkSecondary, fontSize: fontSize.sm },
  bracketNameWon: { color: colors.ink, fontWeight: fontWeight.bold },
  bracketVs: { color: colors.inkMuted, fontSize: fontSize.xs },
  bracketNow: { color: colors.electric, fontSize: fontSize.sm, fontWeight: fontWeight.heavy },
});
