import { StyleSheet } from "react-native";

import { colors, fontSize, fontWeight, radius, spacing } from "../../theme/tokens";

export const raceStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  screenReaderOnly: {
    position: "absolute",
    left: -10000,
    width: 1,
    height: 1,
    overflow: "hidden",
  },
  content: { alignItems: "center", paddingHorizontal: spacing(5), gap: spacing(5) },
  header: {
    width: "100%",
    maxWidth: 420,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing(3),
  },
  title: { color: colors.textPrimary, fontSize: fontSize.lg, fontWeight: fontWeight.heavy },
  section: { width: "100%", maxWidth: 420, gap: spacing(3) },
  sectionLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  modeToggle: {
    flexDirection: "row",
    gap: spacing(2),
  },
  modeOption: {
    flex: 1,
    minHeight: 76,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.md,
    padding: spacing(3),
    gap: spacing(1),
  },
  modeOptionActive: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  modeTitle: { color: colors.textPrimary, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  modeTitleActive: { color: colors.accent },
  modeDescription: { color: colors.textMuted, fontSize: fontSize.xs, lineHeight: 16 },
  chips: { flexDirection: "row", gap: spacing(2) },
  chip: {
    flex: 1,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    alignItems: "center",
    gap: 1,
  },
  chipActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  chipText: { color: colors.textPrimary, fontSize: fontSize.lg, fontWeight: fontWeight.heavy },
  chipUnit: { color: colors.textMuted, fontSize: fontSize.xs },
  chipTextActive: { color: colors.bg },
  input: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3.5),
    paddingVertical: spacing(3),
    color: colors.textPrimary,
    fontSize: fontSize.md,
  },
  card: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.lg,
    padding: spacing(4),
    gap: spacing(2),
  },
  cardRaised: {
    backgroundColor: colors.surfaceRaised,
    borderColor: colors.accent,
  },
  cardNext: {
    backgroundColor: colors.accentBlueSoft,
    borderColor: colors.accentBlue,
  },
  cardHeadRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing(2),
  },
  cardHeading: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  empty: { color: colors.textMuted, fontSize: fontSize.sm, lineHeight: 19 },
  carSummary: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing(3),
    flex: 1,
  },
  carText: { flex: 1, gap: spacing(0.5) },
  carName: { color: colors.textPrimary, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  carMeta: { color: colors.textMuted, fontSize: fontSize.xs },
  readinessPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing(2),
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.pill,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(3),
  },
  readinessDot: { width: 9, height: 9, borderRadius: radius.pill },
  readinessLabel: { color: colors.textPrimary, fontSize: fontSize.sm, fontWeight: fontWeight.medium },
  readinessCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: colors.surface,
    borderColor: colors.warn,
    borderWidth: 1,
    borderRadius: radius.md,
    padding: spacing(3),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing(3),
  },
  readinessText: { flex: 1, gap: spacing(1) },
  readinessTitle: { color: colors.textPrimary, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  readinessDetail: { color: colors.textSecondary, fontSize: fontSize.xs, lineHeight: 16 },
  recoveryLink: { color: colors.accentBlue, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  actionRow: { flexDirection: "row", gap: spacing(2) },
  flex1: { flex: 1 },
  primaryBtn: {
    backgroundColor: colors.accent,
    borderRadius: radius.md,
    paddingVertical: spacing(3.5),
    paddingHorizontal: spacing(3),
    alignItems: "center",
    justifyContent: "center",
  },
  primaryBtnText: { color: colors.bg, fontSize: fontSize.md, fontWeight: fontWeight.heavy },
  ghostBtn: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    paddingHorizontal: spacing(3),
    alignItems: "center",
    justifyContent: "center",
  },
  ghostBtnText: { color: colors.textPrimary, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  smallBtn: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.sm,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(2.5),
  },
  smallBtnText: { color: colors.accentBlue, fontSize: fontSize.xs, fontWeight: fontWeight.bold },
  removeBtnText: { color: colors.danger, fontSize: fontSize.xs, fontWeight: fontWeight.bold },
  dangerBtn: {
    backgroundColor: colors.surface,
    borderColor: colors.danger,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: spacing(3.5),
    paddingHorizontal: spacing(3),
    alignItems: "center",
  },
  dangerBtnText: { color: colors.danger, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  btnDisabled: { opacity: 0.45 },
  btnDisabledText: { color: colors.textMuted },
  pressed: { opacity: 0.7 },
  lineupLabel: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  lineupName: { color: colors.textPrimary, fontSize: fontSize.xl, fontWeight: fontWeight.heavy },
  lineupNameNext: { color: colors.textPrimary, fontSize: fontSize.lg, fontWeight: fontWeight.bold },
  lineupActions: { flexDirection: "row", flexWrap: "wrap", gap: spacing(2) },
  queueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing(3),
    paddingVertical: spacing(2.5),
    borderTopWidth: 1,
    borderTopColor: colors.surfaceAlt,
  },
  queueBody: { flex: 1, gap: spacing(0.5) },
  queueName: { color: colors.textPrimary, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  queueMeta: { color: colors.textMuted, fontSize: fontSize.xs },
  queueActions: { flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-end", gap: spacing(1.5) },
  countdown: {
    width: "100%",
    maxWidth: 420,
    alignItems: "center",
    gap: spacing(4),
    paddingVertical: spacing(6),
  },
  countNum: {
    color: colors.accent,
    fontSize: 140,
    fontWeight: fontWeight.heavy,
    fontVariant: ["tabular-nums"],
  },
  countLabel: { color: colors.textSecondary, fontSize: fontSize.md },
  racerEyebrow: {
    color: colors.accent,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  racerHeading: { color: colors.textPrimary, fontSize: fontSize.xl, fontWeight: fontWeight.heavy },
  lapHero: { alignItems: "center", paddingVertical: spacing(2), gap: spacing(1) },
  lapHeroNum: {
    color: colors.textPrimary,
    fontSize: 72,
    fontWeight: fontWeight.heavy,
    fontVariant: ["tabular-nums"],
  },
  lapHeroOf: { color: colors.textMuted, fontSize: fontSize.xl, fontWeight: fontWeight.bold },
  lapHeroLabel: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  liveRow: { flexDirection: "row", gap: spacing(2) },
  liveStat: {
    flex: 1,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    paddingHorizontal: spacing(2),
    alignItems: "center",
    gap: 2,
  },
  liveStatLabel: { color: colors.textMuted, fontSize: fontSize.xs, textAlign: "center" },
  liveStatValue: {
    color: colors.textPrimary,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    fontVariant: ["tabular-nums"],
  },
  liveStatValueHot: { color: colors.accent },
  lapRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: spacing(2),
    borderTopWidth: 1,
    borderTopColor: colors.surfaceAlt,
  },
  lapNum: { color: colors.textSecondary, fontSize: fontSize.sm },
  lapRight: { flexDirection: "row", alignItems: "center", gap: spacing(2) },
  lapTime: {
    color: colors.textPrimary,
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    fontVariant: ["tabular-nums"],
  },
  lapTimeBest: { color: colors.accent },
  bestTag: { color: colors.accent, fontSize: fontSize.xs, fontWeight: fontWeight.bold, letterSpacing: 1 },
  resultHero: { alignItems: "center", gap: spacing(1), paddingVertical: spacing(2) },
  resultHeroLabel: {
    color: colors.accent,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.heavy,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  resultHeroTime: {
    color: colors.textPrimary,
    fontSize: 56,
    fontWeight: fontWeight.heavy,
    fontVariant: ["tabular-nums"],
  },
  resultHeroSub: { color: colors.textSecondary, fontSize: fontSize.sm },
  nextUpText: { color: colors.accentBlue, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  shareBtn: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    alignItems: "center",
  },
  shareBtnText: { color: colors.accent, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  clearText: { color: colors.textMuted, fontSize: fontSize.xs, fontWeight: fontWeight.bold },
  leaderboardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing(3),
    paddingVertical: spacing(2),
    borderTopWidth: 1,
    borderTopColor: colors.surfaceAlt,
  },
  leaderboardRank: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    fontWeight: fontWeight.heavy,
    width: 22,
    textAlign: "center",
  },
  leaderboardRankTop: { color: colors.accent },
  leaderboardMid: { flex: 1 },
  leaderboardPlayer: { color: colors.textPrimary, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  leaderboardMeta: { color: colors.textMuted, fontSize: fontSize.xs },
  leaderboardTime: {
    color: colors.textPrimary,
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    fontVariant: ["tabular-nums"],
  },
  leaderboardTimeTop: { color: colors.accent },
});
